### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by pr0tools** [RundesBalli/pr0tools#2]
- Alle Badges https://pr0gramm.com/new/3125123
- Suchsyntax https://pr0gramm.com/new/2782197
- Farben zum Copy Pasten https://pr0tools.github.io/pr0tools/ (Sidebar)

**Comment by RundesBalli** [comment]
Suchsyntax ist in der Suche selbst verlinkt und die Farben sind in den Eckdaten von @holzmaster verlinkt und wurden der Übersicht halber nicht mit aufgenommen. In den Eckdaten stehen auch noch die anderen Farben des pr0gramms.
