### ISSUE TITLE
Projekt s0ße hinzufügen

### ISSUE THREAD

**Issue by blubbll** [RundesBalli/pr0tools#4]
https://github.com/blubbll/pr0-source
https://s0sse.link/

Damit können Nutzer ihre Soßen editieren.

**Comment by RundesBalli** [comment]
Hallo,

das Editieren der Quelllinks ist nach Rücksprache mit der pr0gramm Administration nicht erwünscht, weshalb ich das Projekt nicht verlinken werde.

Danke für die Einsendung und viele Grüße

RB
